### ISSUE TITLE
userstory-7_FilterFunction

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone-project#13]
## Value Proposition

**As a** user

**I need** a filter function

**to be able to** see which food is available during specific periods within the year.

## Description

![Saisonkalender - Alle Filter](https://user-images.githubusercontent.com/115747088/212903233-24a245a6-ebbe-4de8-9b7d-1cd607def8ad.png)
![Saisonkalender - Obst Filter](https://user-images.githubusercontent.com/115747088/212903241-0832b384-c99d-40b9-9a3e-4e750795c3e8.png)
![Saisonkalender - Gemüse Filter](https://user-images.githubusercontent.com/115747088/212903243-24514281-ecdd-4589-bc75-df1abda956f3.png)

## Acceptance Criteria

- [ ] Header of the chosen month and food is displayed correctly.
- [ ] FoodCards are displayed correctly in order of the clicked filter criteria.

## Tasks

- [ ] work on branch
- [ ] working with useStates and spreaded arrays into a variable
- [ ] render header elements
- [ ] render related FoodCards
- [ ] create pull request
- [ ] QA
- [ ] merge in main
