### ISSUE TITLE
userstory-4_AddFavorite

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone-project#7]
## Value Proposition

**As a** user

**I need** an option to add foods as favorite

**to be able to** have a list of all favorite fruits and vegetables.

## Description

![userstory-4_AddFavorite2](https://user-images.githubusercontent.com/115747088/208243667-8803639c-fa79-4b53-8b86-b498f8393b2e.png)

![userstory-4_AddFavorite1](https://user-images.githubusercontent.com/115747088/208243663-c9e098e0-e1be-458a-9d54-ccbb63975e27.png)

## Acceptance Criteria

- [ ] Favorite Icon is clickable and adds desired food to favorite list
- [ ] Favorite Icon changes from unfilled to filled after clicking it.

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] work on branch
- [ ] add favorite icon (filled and unfilled) to assets in project
- [ ] create handleclick function to icon which renders a list of favorite foods in favorite page
- [ ] create pull request
- [ ] QA
- [ ] merge in main
