### ISSUE TITLE
userstory-5_RemoveFavorite

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone-project#8]
## Value Proposition

**As a** user

**I need** an option to remove favorite foods

**to be able to** see an updated favorite list of fruits and vegetables.

## Description

![userstory-5_RemoveFavorite1](https://user-images.githubusercontent.com/115747088/208244344-128d54f1-46ef-435e-9d3f-46c389b735b9.png)

![userstory-5_RemoveFavorite2](https://user-images.githubusercontent.com/115747088/208244351-4708aaef-33ad-4cea-925d-de357f095060.png)

## Acceptance Criteria

- [ ] Remove Favorite Icon is clickable and remove desired food from favorite list
- [ ] Remove Favorite Icon changes from filled to unfilled after clicking it.

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] work on branch
- [ ] add remove favorite icon to assets in project
- [ ] create handClick function to icon which removes the food and renders an updated list in Favorite List component (created in earlier userstory)
- [ ] create pull request
- [ ] QA
- [ ] merge in main
