### ISSUE TITLE
userstory-6_DetailPage

### ISSUE THREAD

**Issue by altanguellue** [altanguellue/capstone-project#9]
## Value Proposition

**As a** user

**I need** detailed information of a food

**to be able to** handle or store the fruits and vegetables.

## Description

![userstory-6_DetailPage](https://user-images.githubusercontent.com/115747088/208244611-beabe361-f7cb-4602-bb7e-9a0f9ed78ae6.png)

## Acceptance Criteria

- [ ] describe every scenario in detail
- [ ] Header of the food is displayed
- [ ] There's an image of the food
- [ ] more detailed information which as storing the food, tipps and help (p elements)

## Tasks

- [ ] work on branch
- [ ] update data.js in the lib folder (add more information to the dataFoods)
- [ ] create DetailPage component
- [ ] render h2, img and p elements
- [ ] create pull request
- [ ] QA
- [ ] merge in main

**Comment by Hirnstromwelle** [comment]
Hi Altan,

zuerst: dein Layout ist Mega! : )
Die akzeptablen Kriterien sind verständlich. Bei den Task: Dein Array und Text mit p Elementen erweitert. Kann man definitiv so für eine US umsetzen. Grüner Haken is raus.  : ))
